# Generated by Django 3.0.8 on 2020-07-24 09:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0002_auto_20200724_0820'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collections',
            unique_together={('title', 'owner')},
        ),
    ]
